services:
  db:
    image: postgres:latest
    ports:
      - "5439:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: 1

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080